spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        #   search-locations: file:///C:/Cours/spring%20could/adam-spring-cloud/config-repo
        git:
          uri: https://github.com/AdamBahroun/repo-config.git
          default-label: main
          clone-on-start: true

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: '*'